name: Build and push

env:
  IMAGE_NAME: ghcr.io/sendinblue/github-actions-runner

on:
  push:
    branches:
      - 'main'
    tags:
      - '*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Determine the image tag
        id: image-metadata
        run: |
          REF_NAME=$(echo ${GITHUB_REF#refs/*/} | sed -e 's/^v//')
          IMAGE_TAG=$(printf ${REF_NAME} | tr -c '[[:alnum:]]._-' '_')
          if [[ "${REF_NAME}" == "main" ]]; then IMAGE_TAG=latest; fi
          echo "::set-output name=image-tag::${IMAGE_TAG}"

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: $IMAGE_NAME:${{ steps.image-metadata.outputs.image-tag }}

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}
